name: BuildRunner

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - ".github/workflows/build_runner.yml"
      - "src/build_runner/**"
      # Ensure that the build runner checks get run when the minimum Zig version gets modified
      - "build.zig"
      - "build.zig.zon"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check_build_runner:
    if: github.repository_owner == 'zigtools'
    strategy:
      matrix:
        include:
          - zig-version: 0.13.0
            build-runner-file: 0.12.0.zig
          - zig-version: 0.13.0
            build-runner-file: 0.13.0.zig # The Zig 0.12.0 build runner is also compatible with Zig 0.13.0
          - zig-version: 0.12.0
            build-runner-file: 0.12.0.zig
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Grab zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}
          cache: false

      - name: Create temp zig project
        run: |
          mkdir $RUNNER_TEMP/TEMP_ZIG_PROJECT
          cd $RUNNER_TEMP/TEMP_ZIG_PROJECT
          zig init

      - name: Check build_runner builds
        run: |
          cd $RUNNER_TEMP/TEMP_ZIG_PROJECT
          zig build --build-runner $GITHUB_WORKSPACE/src/build_runner/${{ matrix.build-runner-file }}
