name: BuildRunner

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - ".github/workflows/build_runner.yml"
      - "src/build_runner/**"
      # Ensure that the build runner checks get run when the minimum Zig version gets modified
      - "build.zig"
      - "build.zig.zon"
  workflow_dispatch:

jobs:
  check_build_runner:
    strategy:
      fail-fast: false
      matrix:
        include:
          - zig-version: 0.15.1
          # - zig-version: mach-latest
          # Zig master is handled by 'zig build test' in the main CI
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}

      - name: Create temp zig project
        run: |
          mkdir $RUNNER_TEMP/TEMP_ZIG_PROJECT
          cd $RUNNER_TEMP/TEMP_ZIG_PROJECT
          zig init

      - name: Check build_runner builds
        run: |
          cd $RUNNER_TEMP/TEMP_ZIG_PROJECT
          zig build --build-runner $GITHUB_WORKSPACE/src/build_runner/build_runner.zig
